### ISSUE TITLE
Exchanges & vhosts

### ISSUE THREAD

**Issue by mjtice** [nexylan/graylog-rabbitmq#12]
Hi, I'm looking at this plugin and it looks like it connects to the default vhost and publishes directly to a queue.

I was thinking about creating a PR that includes the vhost and an exchange - but before I do that I was wondering if there was a specific reason this wasn't added?

**Comment by henri9813** [comment]
Hello,

Thanks for your contribution.

This was not handled because in our main goal, our rabbitmq has only one VHOST ( dedicated rabbitmq ).

We don't use Vhost at all.

Howewer, if you want, you can purpose your solution, it will be appreciated ! :-) 


Best regards;

**Comment by mjtice** [comment]
Sounds good.  I created
https://github.com/nexylan/graylog-rabbitmq/pull/13
